# Generated by Django 3.2 on 2024-01-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
